spring.application.name="PORTAL_DE_COMPRAS_EN_LINEA"
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PORTAL_DE_COMPRAS_EN_LINEA;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=katty2023
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9001
